// Demo: register the custom `tertiary` semantic color at the type level so
// `color="tertiary"` autocompletes + type-checks on every @vyui/kit component.
// This is the types half of the "add a color" flow (see README "Adding a
// custom color"); pair with src/index.ts (runtime), tailwind.config.ts
// (Tailwind) and src/index.css (CSS vars). Can be generated by
// `@vyui/kit/scripts/gen-colors.mjs`.
import '@vyui/kit'

declare module '@vyui/kit' {
  interface VyuiColorRegistry {
    tertiary: true
  }
}
