// AUTO-GENERATED by tools/gen-playground-registry.ts — do not edit.
// Add an example SFC under src/examples/** and re-run the playground build.
import type { Component } from 'vue'

import AccordionAnatomy from './accordion/AccordionAnatomy.vue'
import AccordionControlled from './accordion/AccordionControlled.vue'
import AccordionDisabled from './accordion/AccordionDisabled.vue'
import AccordionExample from './accordion/AccordionExample.vue'
import AccordionMultiple from './accordion/AccordionMultiple.vue'
import ActionSheetExample from './action-sheet/ActionSheetExample.vue'
import ActionSheetGrouped from './action-sheet/ActionSheetGrouped.vue'
import AlertClosable from './alert/AlertClosable.vue'
import AlertExample from './alert/AlertExample.vue'
import AlertVariants from './alert/AlertVariants.vue'
import AspectRatioExample from './aspect-ratio/AspectRatioExample.vue'
import AspectRatioVariants from './aspect-ratio/AspectRatioVariants.vue'
import AvatarGroupExample from './avatar-group/AvatarGroupExample.vue'
import AvatarGroupMixed from './avatar-group/AvatarGroupMixed.vue'
import AvatarChip from './avatar/AvatarChip.vue'
import AvatarExample from './avatar/AvatarExample.vue'
import AvatarSizes from './avatar/AvatarSizes.vue'
import IconColor from './icon/IconColor.vue'
import IconExample from './icon/IconExample.vue'
import IconSize from './icon/IconSize.vue'
import InputDisabled from './input/InputDisabled.vue'
import InputExample from './input/InputExample.vue'
import InputIcon from './input/InputIcon.vue'
import InputVariants from './input/InputVariants.vue'
import IslandButtonExample from './island-button/IslandButtonExample.vue'
import IslandGroupExample from './island-group/IslandGroupExample.vue'
import IslandExample from './island/IslandExample.vue'
import KeyboardAwareExample from './keyboard-aware/KeyboardAwareExample.vue'
import LabelExample from './label/LabelExample.vue'
import ModalExample from './modal/ModalExample.vue'
import NumberFieldExample from './number-field/NumberFieldExample.vue'
import PinInputExample from './pin-input/PinInputExample.vue'
import PlaceholderExample from './placeholder/PlaceholderExample.vue'
import PlaceholderLayout from './placeholder/PlaceholderLayout.vue'
import ProgressExample from './progress/ProgressExample.vue'
import ProgressIndeterminate from './progress/ProgressIndeterminate.vue'
import ProgressStatus from './progress/ProgressStatus.vue'
import ProgressSteps from './progress/ProgressSteps.vue'
import ProgressVertical from './progress/ProgressVertical.vue'
import RadioGroupExample from './radio-group/RadioGroupExample.vue'
import RatingExample from './rating/RatingExample.vue'
import SelectExample from './select/SelectExample.vue'
import SeparatorExample from './separator/SeparatorExample.vue'
import SkeletonExample from './skeleton/SkeletonExample.vue'
import SliderExample from './slider/SliderExample.vue'
import SliderRange from './slider/SliderRange.vue'
import SortableExample from './sortable/SortableExample.vue'
import StepperExample from './stepper/StepperExample.vue'
import SwipeActionExample from './swipe-action/SwipeActionExample.vue'
import SwiperExample from './swiper/SwiperExample.vue'
import SwitchColors from './switch/SwitchColors.vue'
import SwitchExample from './switch/SwitchExample.vue'
import TabsExample from './tabs/TabsExample.vue'
import TextareaExample from './textarea/TextareaExample.vue'
import ToastExample from './toast/ToastExample.vue'
import ToastProgressColor from './toast/ToastProgressColor.vue'
import ToggleGroupExample from './toggle-group/ToggleGroupExample.vue'
import ToggleGroupMultiple from './toggle-group/ToggleGroupMultiple.vue'
import ToggleDisabled from './toggle/ToggleDisabled.vue'
import ToggleExample from './toggle/ToggleExample.vue'
import ToggleText from './toggle/ToggleText.vue'
import TrayExample from './tray/TrayExample.vue'

export const examples: Record<string, Component> = {
  'accordion-anatomy': AccordionAnatomy,
  'accordion-controlled': AccordionControlled,
  'accordion-disabled': AccordionDisabled,
  'accordion-example': AccordionExample,
  'accordion-multiple': AccordionMultiple,
  'action-sheet-example': ActionSheetExample,
  'action-sheet-grouped': ActionSheetGrouped,
  'alert-closable': AlertClosable,
  'alert-example': AlertExample,
  'alert-variants': AlertVariants,
  'aspect-ratio-example': AspectRatioExample,
  'aspect-ratio-variants': AspectRatioVariants,
  'avatar-group-example': AvatarGroupExample,
  'avatar-group-mixed': AvatarGroupMixed,
  'avatar-chip': AvatarChip,
  'avatar-example': AvatarExample,
  'avatar-sizes': AvatarSizes,
  'icon-color': IconColor,
  'icon-example': IconExample,
  'icon-size': IconSize,
  'input-disabled': InputDisabled,
  'input-example': InputExample,
  'input-icon': InputIcon,
  'input-variants': InputVariants,
  'island-button-example': IslandButtonExample,
  'island-group-example': IslandGroupExample,
  'island-example': IslandExample,
  'keyboard-aware-example': KeyboardAwareExample,
  'label-example': LabelExample,
  'modal-example': ModalExample,
  'number-field-example': NumberFieldExample,
  'pin-input-example': PinInputExample,
  'placeholder-example': PlaceholderExample,
  'placeholder-layout': PlaceholderLayout,
  'progress-example': ProgressExample,
  'progress-indeterminate': ProgressIndeterminate,
  'progress-status': ProgressStatus,
  'progress-steps': ProgressSteps,
  'progress-vertical': ProgressVertical,
  'radio-group-example': RadioGroupExample,
  'rating-example': RatingExample,
  'select-example': SelectExample,
  'separator-example': SeparatorExample,
  'skeleton-example': SkeletonExample,
  'slider-example': SliderExample,
  'slider-range': SliderRange,
  'sortable-example': SortableExample,
  'stepper-example': StepperExample,
  'swipe-action-example': SwipeActionExample,
  'swiper-example': SwiperExample,
  'switch-colors': SwitchColors,
  'switch-example': SwitchExample,
  'tabs-example': TabsExample,
  'textarea-example': TextareaExample,
  'toast-example': ToastExample,
  'toast-progress-color': ToastProgressColor,
  'toggle-group-example': ToggleGroupExample,
  'toggle-group-multiple': ToggleGroupMultiple,
  'toggle-disabled': ToggleDisabled,
  'toggle-example': ToggleExample,
  'toggle-text': ToggleText,
  'tray-example': TrayExample,
}
