// AUTO-GENERATED by tools/gen-playground-registry.ts — do not edit.
// Add an example SFC under src/examples/** and re-run the playground build.
import type { Component } from 'vue'

import AccordionAnatomy from './accordion/AccordionAnatomy.vue'
import AccordionControlled from './accordion/AccordionControlled.vue'
import AccordionDisabled from './accordion/AccordionDisabled.vue'
import AccordionExample from './accordion/AccordionExample.vue'
import AccordionMultiple from './accordion/AccordionMultiple.vue'
import ToggleDisabled from './toggle/ToggleDisabled.vue'
import ToggleExample from './toggle/ToggleExample.vue'
import ToggleText from './toggle/ToggleText.vue'

export const examples: Record<string, Component> = {
  'accordion-anatomy': AccordionAnatomy,
  'accordion-controlled': AccordionControlled,
  'accordion-disabled': AccordionDisabled,
  'accordion-example': AccordionExample,
  'accordion-multiple': AccordionMultiple,
  'toggle-disabled': ToggleDisabled,
  'toggle-example': ToggleExample,
  'toggle-text': ToggleText,
}
