#!/usr/bin/env node
/**
 * @vyui/kit — custom color codegen.
 *
 * Generates the two hand-synced artifacts needed to add custom semantic colors
 * with TRUE type parity:
 *   1. a `.d.ts` augmenting `VyuiColorRegistry` so the new colors autocomplete +
 *      typo-check on every component `color` prop;
 *   2. a `.css` block of `--ui-color-<name>-<shade>` vars wired to a Tailwind
 *      palette (the consumer override contract `style.css` documents).
 *
 * It does NOT do the runtime/Tailwind wiring (those are one-liners): you still
 * pass `ui.colors` to the plugin and `createVyuiPreset({ colors })` to Tailwind.
 * The script prints those next steps.
 *
 * Usage:
 *   node scripts/gen-colors.mjs --colors tertiary=indigo,brand=violet --out-dir ./vyui-generated
 *
 * Each `name=palette` maps a new color name to a Tailwind v3 palette. Output
 * files: <out-dir>/vyui-colors.d.ts and <out-dir>/vyui-colors.css.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Kept inline (rather than imported from color-constants.js) so this helper
// ships and runs standalone from a consumer's node_modules. Mirrors
// `SHADES` in `src/theme/color-constants.js`.
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

function parseArgs(argv) {
  const args = { colors: '', outDir: './vyui-generated' }
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--colors') args.colors = argv[++i] ?? ''
    else if (argv[i] === '--out-dir') args.outDir = argv[++i] ?? args.outDir
  }
  return args
}

const { colors, outDir } = parseArgs(process.argv.slice(2))

const pairs = colors
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)
  .map((pair) => {
    const [name, palette] = pair.split('=').map((s) => s.trim())
    if (!name || !palette) {
      console.error(`Invalid --colors entry "${pair}" (expected name=palette)`)
      process.exit(1)
    }
    return { name, palette }
  })

if (pairs.length === 0) {
  console.error('Nothing to generate. Pass --colors name=palette[,name2=palette2].')
  process.exit(1)
}

const dts = `// AUTO-GENERATED by @vyui/kit scripts/gen-colors.mjs — do not edit by hand.
// Adds custom semantic colors to every component \`color\` prop type.
import '@vyui/kit'

declare module '@vyui/kit' {
  interface VyuiColorRegistry {
${pairs.map(({ name }) => `    ${name}: true`).join('\n')}
  }
}
`

const css = `/* AUTO-GENERATED by @vyui/kit scripts/gen-colors.mjs — do not edit by hand. */
/* Import this after @vyui/kit/style.css. */
:root {
${pairs
  .map(({ name, palette }) =>
    [`  /* ${name} → ${palette} */`]
      .concat(SHADES.map((shade) => `  --ui-color-${name}-${shade}: theme('colors.${palette}.${shade}');`))
      .concat([`  --ui-${name}: theme('colors.${palette}.500');`])
      .join('\n'),
  )
  .join('\n\n')}
}
`

const absOut = resolve(process.cwd(), outDir)
mkdirSync(absOut, { recursive: true })
const dtsPath = resolve(absOut, 'vyui-colors.d.ts')
const cssPath = resolve(absOut, 'vyui-colors.css')
writeFileSync(dtsPath, dts)
writeFileSync(cssPath, css)

const names = pairs.map((p) => p.name)
console.log(`Generated:
  ${dtsPath}
  ${cssPath}

Wire up the remaining two steps:
  1. Runtime — register the colors with the plugin:
       app.use(VyUI, { ui: { colors: [...COLORS, ${names.map((n) => `'${n}'`).join(', ')}] } })
  2. Tailwind — extend the preset (import COLORS from /tailwind so the config
     stays light under jiti):
       import { createVyuiPreset, COLORS } from '@vyui/kit/tailwind'
       presets: [lynxPreset, createVyuiPreset({ colors: [...COLORS, ${names.map((n) => `'${n}'`).join(', ')}] })]

  Then ensure the generated .d.ts is in your tsconfig 'include' and the .css is imported.`)
