/**
 * Registry of every component and utility currently exported by vyui.
 *
 * Generated by a file-by-file audit of `packages/core/src/*​/index.ts`
 * (2026-05-19). This is the vyui equivalent of reka-ui's `components`
 * constant — but it lists **what vyui actually ships**, not the upstream
 * target set. For the gap between this list and the reka-ui target list, see
 * `plans/component-assessment.md` and `plans/plan.md` § Phases (Phase 5).
 *
 * Keep this file in sync when adding/removing a component or sub-component.
 */

/** Components ported from reka-ui (Lynx render layer, same public API). */
export const components = {
  accordion: [
    'AccordionRoot',
    'AccordionItem',
    'AccordionHeader',
    'AccordionTrigger',
    'AccordionContent',
  ] as const,

  alertDialog: [
    'AlertDialogRoot',
    'AlertDialogTrigger',
    'AlertDialogPortal',
    'AlertDialogContent',
    'AlertDialogOverlay',
    'AlertDialogCancel',
    'AlertDialogAction',
    'AlertDialogTitle',
    'AlertDialogDescription',
  ] as const,

  checkbox: [
    'CheckboxGroupRoot',
    'CheckboxRoot',
    'CheckboxIndicator',
  ] as const,

  collapsible: [
    'CollapsibleRoot',
    'CollapsibleTrigger',
    'CollapsibleContent',
  ] as const,

  combobox: [
    'ComboboxRoot',
    'ComboboxInput',
    'ComboboxAnchor',
    'ComboboxEmpty',
    'ComboboxTrigger',
    'ComboboxCancel',
    'ComboboxGroup',
    'ComboboxLabel',
    'ComboboxContent',
    'ComboboxViewport',
    'ComboboxItem',
    'ComboboxItemIndicator',
    'ComboboxSeparator',
    'ComboboxArrow',
    'ComboboxPortal',
  ] as const,

  dialog: [
    'DialogRoot',
    'DialogTrigger',
    'DialogPortal',
    'DialogContent',
    'DialogOverlay',
    'DialogClose',
    'DialogTitle',
    'DialogDescription',
  ] as const,

  dropdownMenu: [
    'DropdownMenuRoot',
    'DropdownMenuTrigger',
    'DropdownMenuPortal',
    'DropdownMenuContent',
    'DropdownMenuItem',
    'DropdownMenuGroup',
    'DropdownMenuSeparator',
    'DropdownMenuCheckboxItem',
    'DropdownMenuItemIndicator',
    'DropdownMenuLabel',
    'DropdownMenuRadioGroup',
    'DropdownMenuRadioItem',
    'DropdownMenuSub',
    'DropdownMenuSubContent',
    'DropdownMenuSubTrigger',
  ] as const,

  label: [
    'Label',
  ] as const,

  numberField: [
    'NumberFieldRoot',
    'NumberFieldInput',
    'NumberFieldIncrement',
    'NumberFieldDecrement',
  ] as const,

  pagination: [
    'PaginationRoot',
    'PaginationList',
    'PaginationListItem',
    'PaginationFirst',
    'PaginationPrev',
    'PaginationNext',
    'PaginationLast',
    'PaginationEllipsis',
  ] as const,

  pinInput: [
    'PinInputRoot',
    'PinInputInput',
  ] as const,

  popover: [
    'PopoverRoot',
    'PopoverTrigger',
    'PopoverPortal',
    'PopoverContent',
    'PopoverClose',
    'PopoverAnchor',
  ] as const,

  progress: [
    'ProgressRoot',
    'ProgressIndicator',
  ] as const,

  radioGroup: [
    'RadioGroupRoot',
    'RadioGroupItem',
    'RadioGroupIndicator',
  ] as const,

  rating: [
    'RatingRoot',
    'RatingItem',
    'RatingItemIndicator',
  ] as const,

  select: [
    'SelectRoot',
    'SelectTrigger',
    'SelectPortal',
    'SelectContent',
    'SelectViewport',
    'SelectGroup',
    'SelectLabel',
    'SelectItem',
    'SelectItemText',
    'SelectItemIndicator',
    'SelectSeparator',
    'SelectValue',
    'SelectIcon',
  ] as const,

  separator: [
    'Separator',
  ] as const,

  slider: [
    'SliderRoot',
    'SliderTrack',
    'SliderRange',
    'SliderThumb',
  ] as const,

  stepper: [
    'StepperRoot',
    'StepperItem',
    'StepperTrigger',
    'StepperIndicator',
    'StepperSeparator',
    'StepperTitle',
    'StepperDescription',
  ] as const,

  switch: [
    'SwitchRoot',
    'SwitchThumb',
  ] as const,

  tabs: [
    'TabsRoot',
    'TabsList',
    'TabsTrigger',
    'TabsContent',
    'TabsIndicator',
  ] as const,

  toast: [
    'ToastProvider',
    'ToastRoot',
    'ToastViewport',
    'ToastTitle',
    'ToastDescription',
    'ToastAction',
    'ToastClose',
  ] as const,

  toggle: [
    'Toggle',
    'ToggleRoot',
  ] as const,

  toggleGroup: [
    'ToggleGroupRoot',
    'ToggleGroupItem',
  ] as const,

  // Utility components
  configProvider: [
    'ConfigProvider',
  ] as const,

  presence: [
    'Presence',
  ] as const,

  primitive: [
    'Primitive',
    'Slot',
  ] as const,
}

/** vyui originals — no reka-ui equivalent. See `plans/plan.md` § Phase 4. */
export const originals = {
  button: [
    'Button',
  ] as const,

  form: [
    'FormRoot',
    'FormField',
    'FormSubmitButton',
  ] as const,

  islandContainer: [
    'IslandContainer',
  ] as const,

  lazyComponent: [
    'LazyComponent',
  ] as const,

  /** Bare `<list>` primitive — pair with `ListItem`. FeedList composes on top. */
  list: [
    'List',
    'ListItem',
  ] as const,

  swiper: [
    'SwiperRoot',
    'SwiperItem',
  ] as const,

  /** Store-based portal — vyui's Teleport replacement (Lynx has no Teleport). */
  overlayRoot: [
    'OverlayRoot',
  ] as const,
}

/** Exported composables / helpers. */
export const utilities = {
  utilities: [
    'createContext',
    'useDirection',
    'useEmitAsProps',
    'useFilter',
    'useForwardExpose',
    'useForwardProps',
    'useForwardPropsEmits',
    'useId',
    'useLocale',
    'useStateMachine',
    'withDefault',
  ] as const,

  /** Phase 0 Lynx-native composables — replace DOM-coupled reka-ui equivalents. */
  composables: [
    'useResizeObserver',
    'useElementRect',
    'useFocus',
    'useScrollTo',
    'useDismissableLayer',
  ] as const,
}

export type Components = typeof components
export type Originals = typeof originals
export type Utilities = typeof utilities
