/**
 * Semantic color tokens exposed to component `color` variants. These names
 * resolve to Tailwind color scales via CSS variables at runtime (mirrors the
 * nuxt/ui v3 convention). The CSS layer that maps `--ui-color-primary-500` →
 * an actual tailwind scale is generated separately and not part of this file.
 *
 * The raw constants live in `./color-constants` (a plain `.js` shared with the
 * build-time `tailwind.js` plane). This module re-exports them for the TS plane
 * and adds the runtime `resolveColors` helper + the public `Color` type.
 */
import type { AppConfig } from '@/lib/vyui/types'
import { ALL_COLORS, COLORS, NEUTRAL } from '@/lib/vyui/theme/color-constants'

export { ALL_COLORS, COLORS, NEUTRAL }

/**
 * Type-level registry of every color a component `color` prop accepts. The
 * default members mirror `ALL_COLORS` (keep them in sync). This is an
 * `interface` precisely so consumers can extend it via module augmentation to
 * get TRUE parity — added colors autocomplete + typo-check everywhere, no build
 * plugin required (the vue-router `RouteNamedMap` pattern):
 *
 * ```ts
 * // env.d.ts in the consuming app (or generated by `scripts/gen-colors.mjs`)
 * declare module '@vyui/kit' {
 *   interface VyuiColorRegistry { tertiary: true }
 * }
 * ```
 *
 * After that, `<VyButton color="tertiary">` is type-checked and autocompletes,
 * tracking the consumer's exact configured set. Pair with the runtime
 * (`appConfig.ui.colors`) + Tailwind (`createVyuiPreset({ colors })`) + CSS-var
 * steps — see the "Adding a color" docs.
 */
export interface VyuiColorRegistry {
  primary: true
  secondary: true
  success: true
  info: true
  warning: true
  error: true
  neutral: true
}

/**
 * Public union of every color a component `color` prop accepts. Derived from
 * `VyuiColorRegistry` so consumer module augmentation flows through to every
 * component's `color` prop type.
 */
export type Color = keyof VyuiColorRegistry

/**
 * Resolve the active color list from app config. Falls back to the default
 * `COLORS` when the consumer hasn't set `appConfig.ui.colors`, then always
 * appends `neutral` (kept out of the configurable list — nuxt/ui parity).
 * De-duplicates in case a consumer's list already contains `neutral`.
 */
export function resolveColors(appConfig: AppConfig): Color[] {
  const configured = appConfig.ui.colors ?? COLORS
  // Typed as the default `Color` union: theme builders take `Color[]` so their
  // compoundVariants `color` field matches the color-variant keys under `tv`.
  // Runtime-added custom colors still flow through (the codegen plugin refines
  // the static types to the consumer's exact set).
  return [...new Set([...configured, NEUTRAL])] as Color[]
}
