// Regenerates src/icons.generated.ts with just the iconify glyphs this demo
// (and @vyui/kit's defaults) actually reference. Registering the FULL
// icon-park-outline + lucide sets shipped ~1.5 MB of JSON in the bundle —
// parsed on the background thread at startup and held for the app's lifetime —
// for ~60 used icons.
//
// Run after adding an icon name anywhere in src/ or packages/kit/src/:
//   pnpm gen:icons
// A name the script can't resolve fails the run (typo protection); an icon
// missing from the generated set renders as nothing on device.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const SCAN_DIRS = [
  join(root, 'src'),
  resolve(root, '../../../packages/kit/src'),
]
const OUT_FILE = join(root, 'src/icons.generated.ts')

// Matches the name forms core's Icon resolver accepts for our two registered
// prefixes: `lucide:x`, `i-lucide-x`, `icon-park-outline:x`.
const NAME_RES = [
  [/\bicon-park-outline:([a-z0-9-]+)/g, 'icon-park-outline'],
  [/\blucide:([a-z0-9-]+)/g, 'lucide'],
  [/\bi-lucide-([a-z0-9-]+)/g, 'lucide'],
]

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue
      yield* walk(path)
    }
    else if (/\.(vue|ts|js)$/.test(entry) && path !== OUT_FILE) {
      yield path
    }
  }
}

const used = { 'icon-park-outline': new Set(), 'lucide': new Set() }
for (const dir of SCAN_DIRS) {
  for (const file of walk(dir)) {
    const text = readFileSync(file, 'utf8')
    for (const [re, prefix] of NAME_RES) {
      for (const match of text.matchAll(re)) used[prefix].add(match[1])
    }
  }
}

/** Pick `names` out of a full IconifyJSON, following alias parent chains. */
function subset(set, names) {
  const icons = {}
  const aliases = {}
  const missing = []
  for (const name of [...names].sort()) {
    let current = name
    // Alias entries carry transforms and point at a parent; copy the whole
    // chain so @iconify/utils can resolve it at runtime.
    while (set.aliases?.[current]) {
      aliases[current] = set.aliases[current]
      current = set.aliases[current].parent
    }
    if (set.icons[current]) icons[current] = set.icons[current]
    else missing.push(name)
  }
  const out = { prefix: set.prefix, icons }
  if (Object.keys(aliases).length) out.aliases = aliases
  // Top-level width/height are the defaults for icons that don't set their own.
  if (set.width !== undefined) out.width = set.width
  if (set.height !== undefined) out.height = set.height
  return { out, missing }
}

const sets = {
  'icon-park-outline': JSON.parse(readFileSync(join(root, 'node_modules/@iconify-json/icon-park-outline/icons.json'), 'utf8')),
  'lucide': JSON.parse(readFileSync(join(root, 'node_modules/@iconify-json/lucide/icons.json'), 'utf8')),
}

const generated = {}
for (const [prefix, set] of Object.entries(sets)) {
  const { out, missing } = subset(set, used[prefix])
  if (missing.length)
    throw new Error(`gen-icons: unknown ${prefix} icon(s): ${missing.join(', ')}`)
  generated[prefix] = out
}

const banner = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Regenerate after adding icon names anywhere in src/ or packages/kit/src:
//   pnpm gen:icons
`
const body = [
  `export const iconParkOutline = ${JSON.stringify(generated['icon-park-outline'], null, 2)}\n`,
  `export const lucide = ${JSON.stringify(generated.lucide, null, 2)}\n`,
].join('\n')
writeFileSync(OUT_FILE, `${banner}\n${body}`)

const counts = Object.entries(generated)
  .map(([p, s]) => `${p}: ${Object.keys(s.icons).length} icons`)
  .join(', ')
console.log(`gen-icons: wrote src/icons.generated.ts (${counts})`)
