export const ACCENT = '#3b82f6'
export const ACCENT_LIGHT = '#eff6ff'
export const ACCENT_INDIGO = '#6366f1'
export const ACCENT_INDIGO_LIGHT = '#eef2ff'
export const DANGER = '#ef4444'
export const DANGER_LIGHT = '#fef2f2'

export const TEXT_PRIMARY = '#0f172a'
export const TEXT_SECONDARY = '#64748b'
export const TEXT_MUTED = '#94a3b8'

export const BORDER = '#e2e8f0'
export const SURFACE = '#ffffff'
export const SURFACE_ALT = '#f8fafc'
export const HAIRLINE = '#f1f5f9'
