/**
 * Generates the docs-playground example registry (`src/examples/index.ts`) from
 * the SFCs under `src/examples/**`. Emitting STATIC imports keeps the registry
 * tree-shakeable and avoids `import.meta.glob`, which rspack's parser only
 * partially supports (it warns "Accessing import.meta directly is unsupported"
 * and falls back to a runtime resolve). Adding an example SFC is still the only
 * authoring step — this runs automatically before the playground build.
 *
 * Example ids are the camel→kebab of the file basename, matching the manifest
 * ids produced by `tools/sync-playground.ts` so the keys never drift.
 *
 * Run via `pnpm --filter @vyui/docs playground:build` (before rspeedy build).
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const examplesDir = resolve(root, 'apps/examples/docs-playground/src/examples')

const toKebab = (name: string) =>
  name.replace(/\.vue$/, '').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) return walk(full)
    return entry.name.endsWith('.vue') ? [full] : []
  })
}

// Sorted for stable diffs. Identifier = PascalCase basename (file names already
// are); a duplicate basename across folders would collide, so guard against it.
const files = walk(examplesDir).sort()
const seen = new Map<string, string>()
const entries = files.map((file) => {
  const base = file.split('/').pop()!.replace(/\.vue$/, '')
  const id = toKebab(`${base}.vue`)
  const prior = seen.get(base)
  if (prior) throw new Error(`Duplicate example basename "${base}.vue" (${prior} and ${file}); basenames must be unique.`)
  seen.set(base, file)
  return { ident: base, id, importPath: `./${relative(examplesDir, file)}` }
})

const out = [
  `// AUTO-GENERATED by tools/gen-playground-registry.ts — do not edit.`,
  `// Add an example SFC under src/examples/** and re-run the playground build.`,
  `import type { Component } from 'vue'`,
  ``,
  ...entries.map(e => `import ${e.ident} from '${e.importPath}'`),
  ``,
  `export const examples: Record<string, Component> = {`,
  ...entries.map(e => `  '${e.id}': ${e.ident},`),
  `}`,
  ``,
].join('\n')

writeFileSync(resolve(examplesDir, 'index.ts'), out)
console.log(`[gen-playground-registry] wrote ${entries.length} examples to src/examples/index.ts`)
