/**
 * Syncs the docs-playground into the docs app:
 *
 *   1. Copies the web bundle into `public/` so `<LynxPreview>` can load it
 *      from `/playground/main.web.bundle` (a single self-contained file).
 *   2. Reads every example SFC under the playground's `src/examples/**` and
 *      emits a source manifest so `<ComponentCode>` can show the exact code
 *      that renders in the live preview. Example ids are the camel→kebab of
 *      the file basename (e.g. `AccordionMultiple.vue` -> `accordion-multiple`),
 *      matching the playground's registry keys.
 *
 * Run via `pnpm --filter @vyui/docs playground:build`, which builds first.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { codeToHtml } from 'shiki'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const playground = resolve(root, 'apps/examples/docs-playground')

// 1. Web bundle -> docs public/
const bundleSrc = resolve(playground, 'dist/main.web.bundle')
const publicDir = resolve(root, 'apps/docs/public/playground')
mkdirSync(publicDir, { recursive: true })
copyFileSync(bundleSrc, resolve(publicDir, 'main.web.bundle'))

// 2. Example sources -> generated manifest
const examplesDir = resolve(playground, 'src/examples')

const toKebab = (name: string) =>
  name.replace(/\.vue$/, '').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) return walk(full)
    return entry.name.endsWith('.vue') ? [full] : []
  })
}

// Highlight with the same theme @nuxt/content uses (material-theme-palenight)
// so the Code panel matches the prose ```vue fenced blocks.
const manifest: Record<string, { source: string, highlighted: string }> = {}
for (const file of walk(examplesDir)) {
  const id = toKebab(file.split('/').pop()!)
  const source = readFileSync(file, 'utf8').trimEnd()
  const highlighted = await codeToHtml(source, { lang: 'vue', theme: 'material-theme-palenight' })
  manifest[id] = { source, highlighted }
}

const genDir = resolve(root, 'apps/docs/app/generated')
mkdirSync(genDir, { recursive: true })
writeFileSync(
  resolve(genDir, 'examples.ts'),
  `// AUTO-GENERATED by tools/sync-playground.ts — do not edit.\n`
  + `export const examples: Record<string, { source: string, highlighted: string }> = ${JSON.stringify(manifest, null, 2)}\n`,
)

console.log(`[sync-playground] bundle + ${Object.keys(manifest).length} example sources synced`)
